---
language: ruby
sudo: required
services: docker
cache: bundler
script:
  - ./.build.sh
after_success:
  - ./.publish.sh
before_script:
  - sudo apt-get update
  - sudo apt-get install -y -q docker-engine=$DOCKER_ENGINE_VERSION
