#!/bin/bash
set -e

if [[ "${UID}" != 0 ]]
then
    echo "Switching listen port to 8080"
    cd /tmp
    sed -i -e 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf
    sed -i -e 's/Listen 80$/Listen 8080/' /etc/apache2/ports.conf
fi

exec apache2ctl -DFOREGROUND
